name: Context vars
on: push
jobs:
  context-example:
    runs-on: ubuntu-latest 
    steps:
      - name: context vars example
        run: |
          echo "This is triggered by ${{ github.actor }}"  # This gives you the user who triggered this workflow
          echo "This repo is: ${{github.repository}}"
          echo "This repo is owned by: ${{github.repository_owner}}"
          
      - name: print all the vars under github context vars
        run: echo "${{ toJson(github) }}"  # -> This prints entire context vars under github 

      - name: print the envs
        run: |
          printenv
          echo "$GITHUB_SHA"  # -> The syntax is different when accessing the envs
