name: Build and Deploy
# So, we want to trigger this whole workflow, for some events like: pull request or commits getting to the main branch

on: 
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Step-1 - Building step
        run: echo "Buildig the application"

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Step-2 - Deploying Step
        run: echo "Deploying the app - pr2"
