name: Conditions example - OR
on:  workflow_dispatch
  # push:
  #   branches:
  #     - main
  #     - develop
# on: workflow_dispatch
jobs:
  demo-conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Run for the user - OR
        if: github.actor  == 'VinaySobarad' || github.actor == 'Shinee79'
        # if: github.ref == 'refs/heads/main' -> Even this can be used
        run: echo "Running step-1, and triggered by -> ${{github.actor}}"
      - name: Step 2
        run: echo "Running step-2"
  
