# Outpus are the values returned by one task which is used by another task
# Using outputs we can share the data between tasks/steps
# Sharing the data between the jobs
name: Output example
on: push
jobs:
  output-example:
    outputs:
      version: ${{steps.step1.outputs.version}}  # So, first we need to set the output at the job level, and here version: "", here hte key name can be anything, not necessarily version, like same as the output key
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step1 # We need to create an id, so that we can refer it, while we try to access the output
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT # To store this output, we use a special redirection to a special file in github actions that is: $GITHUB_OUTPUT.
        # Sending this info to this file is stores as an output. So, I would like to use this thing in the next step
      - name: Step two
        run: echo "The version is ${{ steps.step1.outputs.version }}"

# Now between the jobs:
  output-example-jobs-sharing:
    needs: output-example # So, this is mportant, wkt by default all jobs run parallelly, so we need to use this, so that we can easily access the output
    runs-on: ubuntu-latest
    steps:
      - name: Step three
        run: echo "The version is -> ${{ needs.output-example.outputs.version }}" 
  
